# Generated by Django 3.2.6 on 2021-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(blank=True, upload_to='FoodMenu/'),
        ),
    ]
