# Generated by Django 3.2.6 on 2021-08-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210825_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cod', 'Cash On Delivery'), ('upi', 'UPI'), ('googlepay', 'GPay'), ('paytm', 'Paytm'), ('banktransfer', 'Bank Transfer')], max_length=20),
        ),
    ]
