# Generated by Django 3.2.6 on 2021-08-29 07:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(default=core.models.all_item, to='core.OrderItem'),
        ),
    ]
