# Generated by Django 3.2.6 on 2021-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='foodmenus',
            field=models.ImageField(blank=True, upload_to='FoodMenu/'),
        ),
    ]
