# Generated by Django 3.2.6 on 2021-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_foodmenu_foodmenus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleypage', models.ImageField(blank=True, upload_to='Gallery/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
