# Generated by Django 3.2.6 on 2021-08-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantName', models.TextField(max_length=30)),
                ('LogoPicture', models.ImageField(upload_to='Logo/')),
                ('AboutPicture', models.ImageField(upload_to='About/')),
                ('TagLine', models.CharField(max_length=200)),
                ('Discription', models.TextField()),
                ('ContactNo', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='galleypage',
            field=models.ImageField(upload_to='Gallery/'),
        ),
    ]
