# Generated by Django 3.2.6 on 2021-08-21 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20210817_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodmenu',
            old_name='foodmenus',
            new_name='foodmenu',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='galleypage',
            new_name='GalleryPage',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
