# Generated by Django 3.2.6 on 2021-08-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210821_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='employee',
        ),
    ]
