# Generated by Django 3.2.6 on 2021-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_homepagemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemenu',
            name='home_picture',
            field=models.ImageField(blank=True, upload_to='HomePicture/'),
        ),
        migrations.AddField(
            model_name='homepagemenu',
            name='picture_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagemenu',
            name='foodmenu',
            field=models.ImageField(upload_to='HomePicture/'),
        ),
    ]
