# Generated by Django 3.2.6 on 2021-08-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210829_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemenu',
            name='foodmenu',
            field=models.ImageField(blank=True, upload_to='HomePicture/'),
        ),
        migrations.AlterField(
            model_name='homepagemenu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='homepagemenu',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
