# Generated by Django 3.2.6 on 2021-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210829_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemenu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
