# Generated by Django 3.2.6 on 2021-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_homepagemenu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagemenu',
            old_name='home_picture',
            new_name='home_picture_first',
        ),
        migrations.RenameField(
            model_name='homepagemenu',
            old_name='picture_name',
            new_name='title_first',
        ),
        migrations.AddField(
            model_name='homepagemenu',
            name='home_picture_second',
            field=models.ImageField(blank=True, upload_to='HomePicture/'),
        ),
        migrations.AddField(
            model_name='homepagemenu',
            name='home_picture_third',
            field=models.ImageField(blank=True, upload_to='HomePicture/'),
        ),
        migrations.AddField(
            model_name='homepagemenu',
            name='title_second',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepagemenu',
            name='title_third',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
