# Generated by Django 3.2.6 on 2021-08-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210822_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
