# Generated by Django 3.2.6 on 2021-08-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210821_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
