# Generated by Django 3.2.6 on 2021-08-24 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='ProfilePicture/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
